functionsDirectory = "/Users/pawel/Desktop/juicer/PrivateWorkPrivateComputer/callprep-ai-integrations/mcp-server/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/pawel/Desktop/juicer/PrivateWorkPrivateComputer/callprep-ai-integrations/mcp-server/public"
publishOrigin = "config"
base = "/Users/pawel/Desktop/juicer/PrivateWorkPrivateComputer/callprep-ai-integrations/mcp-server"
functions = "/Users/pawel/Desktop/juicer/PrivateWorkPrivateComputer/callprep-ai-integrations/mcp-server/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"